// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ComputeResourceType string

const (
	ComputeResourceType_MicroVm ComputeResourceType = "MicroVm"
)

type NetworkConnectorLastUpdateStatus string

const (
	NetworkConnectorLastUpdateStatus_Failed     NetworkConnectorLastUpdateStatus = "Failed"
	NetworkConnectorLastUpdateStatus_InProgress NetworkConnectorLastUpdateStatus = "InProgress"
	NetworkConnectorLastUpdateStatus_Successful NetworkConnectorLastUpdateStatus = "Successful"
)

type NetworkConnectorLastUpdateStatusReasonCode string

const (
	NetworkConnectorLastUpdateStatusReasonCode_DisallowedByVpcEncryptionControl NetworkConnectorLastUpdateStatusReasonCode = "DisallowedByVpcEncryptionControl"
	NetworkConnectorLastUpdateStatusReasonCode_Ec2RequestLimitExceeded          NetworkConnectorLastUpdateStatusReasonCode = "Ec2RequestLimitExceeded"
	NetworkConnectorLastUpdateStatusReasonCode_InsufficientRolePermissions      NetworkConnectorLastUpdateStatusReasonCode = "InsufficientRolePermissions"
	NetworkConnectorLastUpdateStatusReasonCode_InternalError                    NetworkConnectorLastUpdateStatusReasonCode = "InternalError"
	NetworkConnectorLastUpdateStatusReasonCode_InvalidSecurityGroup             NetworkConnectorLastUpdateStatusReasonCode = "InvalidSecurityGroup"
	NetworkConnectorLastUpdateStatusReasonCode_InvalidSubnet                    NetworkConnectorLastUpdateStatusReasonCode = "InvalidSubnet"
	NetworkConnectorLastUpdateStatusReasonCode_SubnetOutOfIPAddresses           NetworkConnectorLastUpdateStatusReasonCode = "SubnetOutOfIPAddresses"
)

type NetworkConnectorState string

const (
	NetworkConnectorState_ACTIVE        NetworkConnectorState = "ACTIVE"
	NetworkConnectorState_DELETE_FAILED NetworkConnectorState = "DELETE_FAILED"
	NetworkConnectorState_DELETING      NetworkConnectorState = "DELETING"
	NetworkConnectorState_FAILED        NetworkConnectorState = "FAILED"
	NetworkConnectorState_INACTIVE      NetworkConnectorState = "INACTIVE"
	NetworkConnectorState_PENDING       NetworkConnectorState = "PENDING"
)

type NetworkConnectorStateReasonCode string

const (
	NetworkConnectorStateReasonCode_DisallowedByVpcEncryptionControl NetworkConnectorStateReasonCode = "DisallowedByVpcEncryptionControl"
	NetworkConnectorStateReasonCode_Ec2RequestLimitExceeded          NetworkConnectorStateReasonCode = "Ec2RequestLimitExceeded"
	NetworkConnectorStateReasonCode_InsufficientRolePermissions      NetworkConnectorStateReasonCode = "InsufficientRolePermissions"
	NetworkConnectorStateReasonCode_InternalError                    NetworkConnectorStateReasonCode = "InternalError"
	NetworkConnectorStateReasonCode_InvalidSecurityGroup             NetworkConnectorStateReasonCode = "InvalidSecurityGroup"
	NetworkConnectorStateReasonCode_InvalidSubnet                    NetworkConnectorStateReasonCode = "InvalidSubnet"
	NetworkConnectorStateReasonCode_SubnetOutOfIPAddresses           NetworkConnectorStateReasonCode = "SubnetOutOfIPAddresses"
)

type NetworkConnectorType string

const (
	NetworkConnectorType_VPC_EGRESS NetworkConnectorType = "VPC_EGRESS"
)

type NetworkProtocol string

const (
	NetworkProtocol_DualStack NetworkProtocol = "DualStack"
	NetworkProtocol_IPv4      NetworkProtocol = "IPv4"
)

type ThrottleReason string

const (
	ThrottleReason_CallerRateLimitExceeded                           ThrottleReason = "CallerRateLimitExceeded"
	ThrottleReason_ConcurrentInvocationLimitExceeded                 ThrottleReason = "ConcurrentInvocationLimitExceeded"
	ThrottleReason_ConcurrentSnapshotCreateLimitExceeded             ThrottleReason = "ConcurrentSnapshotCreateLimitExceeded"
	ThrottleReason_FunctionInvocationRateLimitExceeded               ThrottleReason = "FunctionInvocationRateLimitExceeded"
	ThrottleReason_ReservedFunctionConcurrentInvocationLimitExceeded ThrottleReason = "ReservedFunctionConcurrentInvocationLimitExceeded"
	ThrottleReason_ReservedFunctionInvocationRateLimitExceeded       ThrottleReason = "ReservedFunctionInvocationRateLimitExceeded"
)
